# ClientFlow AI Suite - Render Deployment Configuration
services:
  - type: web
    name: clientflow-ai-suite-api
    env: node
    plan: starter
    buildCommand: cd api-server && npm install
    startCommand: cd api-server && npm run start:production
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    regions:
      - oregon
    autoDeploy: true
    branch: main
    rootDir: api-server