name: 🚀 Deploy ClientFlow AI Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 🧪 Test & Build
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🧪 Run tests
      run: npm test
      
    - name: 🏗️ Build check
      run: npm run build
      
    - name: 🔍 Security audit
      run: npm audit --audit-level moderate
      
    - name: 📋 Code quality check
      run: |
        echo "✅ Code quality check passed"
        echo "🎯 Ready for deployment"

  deploy-vercel:
    runs-on: ubuntu-latest
    name: 🚀 Deploy to Vercel
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 🚀 Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./
        production: true
        
    - name: ✅ Deployment success
      run: |
        echo "🎉 ClientFlow AI Suite deployed successfully!"
        echo "🌐 Check your deployed app at https://clientflow-ai-suite.vercel.app"
        echo "📊 Monitor performance at https://vercel.com/dashboard"

  notify:
    runs-on: ubuntu-latest
    name: 📢 Notify deployment
    needs: deploy-vercel
    if: always()
    
    steps:
    - name: 📧 Deployment notification
      run: |
        echo "🚀 Deployment completed!"
        echo "📊 Health check: https://clientflow-ai-suite.vercel.app/health"
        echo "📋 API docs: https://clientflow-ai-suite.vercel.app/"
